version: '3.9'

services:

  zeit-service:
    image: jnhck/time_microservice:latest
    container_name: compose-zeitservice
    networks: 
      - local_network

  zeit-service-webapi:
    image: jnhck/time_microservice_webapi:latest
    container_name: compose-webapi-zeitservice
    networks:
      - local_network
    ports:
      - "3000:3000"
    depends_on:
      - zeit-service

networks:
  local_network:
    external: true